"""add agent_traces table

Revision ID: 543e5b7ec2eb
Revises: 002_notnull
Create Date: 2026-07-08 10:12:20.866464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543e5b7ec2eb'
down_revision: Union[str, Sequence[str], None] = '002_notnull'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('gate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_traces_request', 'agent_traces', ['request_id'], unique=False)
    op.create_index('idx_traces_user', 'agent_traces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_traces_user', table_name='agent_traces')
    op.drop_index('idx_traces_request', table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
